import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";
import storybook from "eslint-plugin-storybook";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Generated by graphql-codegen (never edited by hand).
    "src/lib/graphql/generated/**",
    // Storybook static build output.
    "storybook-static/**",
  ]),
  ...storybook.configs["flat/recommended"],
  // Must stay last: turns off rules that conflict with Prettier.
  prettier,
]);

export default eslintConfig;
